// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Provider.Data.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20210408200516_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Data.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnName("normalized_name")
                        .HasColumnType("text");

                    b.Property<int>("StockCount")
                        .HasColumnName("stock_count")
                        .HasColumnType("integer");

                    b.HasKey("ID")
                        .HasName("pk_products");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Name = "Keyboard",
                            NormalizedName = "KEYBOARD",
                            StockCount = 40
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Name = "Mouse",
                            NormalizedName = "MOUSE",
                            StockCount = 20
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Name = "Monitor",
                            NormalizedName = "MONITOR",
                            StockCount = 50
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            Name = "Printer",
                            NormalizedName = "PRINTER",
                            StockCount = 50
                        },
                        new
                        {
                            ID = 5,
                            IsActive = true,
                            Name = "Earphone",
                            NormalizedName = "EARPHONE",
                            StockCount = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
